import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import "./About.css";
import sharad_img from "../images/sharad.jpg";
import sijan_img from "../images/sijan.jpg";
import sidhant_img from "../images/sidhant.jpg";
import satyam_img from "../images/DSC_0010-2.jpg";
function About() {

  return (
    <>
      <div className="navbar">
        <div className="aigon">
          <Link to="/" style={{ textDecoration: 'none' }}>
            <p>DetectAI</p>
          </Link>
        </div>
        <div className="about" >
          <Link to="/about" style={{ textDecoration: 'none', background: 'red' }}>
            <p>ABOUT</p>
          </Link>
        </div>
      </div>
      <section>
        <h3>Users can confidently explore the digital world with DetectAI, a state-of-the-art platform that detects text and faces generated by artificial intelligence.</h3>
        <div className="sections">
        <h2>Our Mission</h2>
        <p>DetectAI's goal is to stop the spread of artificial intelligence (AI)-generated information by offering reliable detection and verification solutions. We support the development of a more secure online community where trust and sincerity rule.</p>
        </div>
        <div className="sections">
        <h2>The Issue</h2>
        <p>The rapid growth of AI technology has resulted in an alarming increase in the spread of synthetic content, posing serious problems to authenticity and reliability online. From fake news articles to manipulated photos, distinguishing authentic information from AI-generated reproductions is becoming increasingly challenging, necessitating the development of effective detection methods.</p>
        </div>
        <div className="sections">
<h2>Our Solution</h2>
<p>By utilizing cutting-edge algorithms and machine learning approaches, DetectAI provides an extensive toolkit designed to precisely detect faces and text generated by artificial intelligence. By providing consumers with the ability to differentiate between real and fake content, our technology helps people make more educated decisions and slows the spread of false information.</p>
          
        </div>
        <div className="sections">

<h2>Our Vision</h2>
<p>Here at DetectAI, we see a day when people and businesses can confidently traverse the digital terrain, knowing that the content they come across is authentic and of high quality. Our vision is to become the national industry leader in AI detection by constant innovation and technological advancement, promoting global confidence and dependability in online interactions.</p>
        </div>
        <div className="sections">
<h2>Meet the Team</h2>
<p>Our team at DetectAI is made up of enthusiastic people committed to expanding the capabilities of AI detection technology. Our developers are highly skilled in machine learning, backend and frontend technology, and cybersecurity, and they contribute a wealth of knowledge and creativity to every facet of our platform.</p>
        </div>

      </section>
      <div className="image-card-container">
      <div className="image-card">
        <img src={sharad_img} alt="Image 1" />
        <p>Sharad Kumar Dahal</p>
      </div>
      <div className="image-card">
        <img src={sidhant_img} alt="Image 2" />
        <p>Sidhant Thakur</p>
      </div>
      <div className="image-card">
        <img src={sijan_img} alt="Image 3" />
        <p>Sijan Dev</p>
      </div>
      <div className="image-card">
        <img src={satyam_img} alt="Image 4" />
        <p>Satyam Kumar Singh</p>
      </div>
    </div>
      
    </>
  );
}

export default About;
